apiVersion: v1
kind: PersistentVolume
metadata:
  name: local
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: /meubanco/
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: xtuser777/database-kubernetes:1.0
        args:
        - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        
        volumeMounts:
        - name: local
          mountPath: /var/lib/mysql/
      volumes:
      - name: local
        persistentVolumeClaim:
          claimName: local
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels: 
    app: php
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: xtuser777/backend-kubernetes:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
